library(data.table)
library(dplyr)
gdp <- fread("gdp.csv", skip = 4, nrows = 190, select = c(1, 2, 4, 5), col.names = c("CountryCode", "Rank", "Country", "GDP"))
edudata <- fread("edudata.csv")
cdata <- merge(gdp, edudata, by = "CountryCode")
nrow(cdata)
tapply(cdata$Rank, cdata$`Income Group`, mean)
cdata$RankGroups <- cut(cdata$Rank, breaks = 5)
table(cdata$RankGroups, cdata$`Income Group`)
