library(quantmod)
library(lubridate)
amzn = getSymbols("AMZN",auto.assign=FALSE)
sampleTimes = index(amzn)
value1 <- grep("^2012", sampleTimes, value = TRUE)
mondy <- wday(value1, label = TRUE)
value2 <- grep("mon", mondy, ignore.case = TRUE, value = FALSE)
length(value1)
length(value2)
